accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.SignupView.as_view(), name="signup"),
    path("login/", auth_views.LoginView.as_view(template_name="accounts/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("<str:username>/", views.UserProfileView.as_view(), name="profile"),
    path("<str:username>/follow/", views.FollowView.as_view(), name="follow"),
    path("<str:username>/unfollow/", views.UnFollowView.as_view(), name="unfollow"),
    path("<str:username>/following_list/", views.FollowingListView.as_view(), name="following_list"),
    path("<str:username>/follower_list/", views.FollowerListView.as_view(), name="follower_list"),
]

mysite/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("tweets/", include("tweets.urls")),
    path("", include("welcome.urls")),
]

if settings.SQL_DEBUG:
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

tweets/urls.py
from django.urls import path

from . import views

app_name = "tweets"

urlpatterns = [
    path("home/", views.HomeView.as_view(), name="home"),
    path("create/", views.TweetCreateView.as_view(), name="create"),
    path("<int:pk>/", views.TweetDetailView.as_view(), name="detail"),
    path("<int:pk>/delete/", views.TweetDeleteView.as_view(), name="delete"),
    path("<int:pk>/like/", views.LikeView.as_view(), name="like"),
    path("<int:pk>/unlike/", views.UnLikeView.as_view(), name="unlike"),
]

accounts/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils import timezone


class User(AbstractUser):
    email = models.EmailField()
    follow = models.ManyToManyField(
        "User",
        through="FollowRelation",
    )


class FollowRelation(models.Model):
    following_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="following")
    followed_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="followed")
    created_at = models.DateTimeField(default=timezone.now, editable=False)

    class Meta:
        constraints = [
            # 重複するリレーションは登録できない
            models.UniqueConstraint(
                fields=["following_user", "followed_user"],
                condition=models.Q(following_user__isnull=False, followed_user__isnull=False),
                name="unique_relation",
                violation_error_message="同じユーザーを複数回フォローすることはできません",
            ),
            # 自分自身をフォローすることはできない
            models.CheckConstraint(
                check=~models.Q(following_user=models.F("followed_user")),
                name="cannot_follow_myself",
                violation_error_message="自分自身をフォローすることはできない",
            ),
        ]

tweets/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone


class Tweet(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="author")
    text = models.CharField(max_length=280)
    created_at = models.DateTimeField(default=timezone.now, editable=False)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, through="Like", related_name="likes")

    def __str__(self):
        return self.text


class Like(models.Model):
    liking_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="liking_user")
    liked_tweet = models.ForeignKey(Tweet, on_delete=models.CASCADE, related_name="liked_tweet")

    class Meta:
        constraints = [
            # 重複するリレーションは登録できない
            models.UniqueConstraint(
                fields=["liking_user", "liked_tweet"],
                condition=models.Q(liking_user__isnull=False, liked_tweet__isnull=False),
                name="unique_like_relation",
                violation_error_message="同じツイートを複数回いいねすることはできません",
            ),
        ]

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()  # グローバル変数として扱う


class SignupForm(UserCreationForm):
    class Meta:
        model = User  # model = get_user_model() は NG
        fields = ("username", "email")

accounts/views.py
from django.contrib.auth import authenticate, get_user_model, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import ValidationError
from django.http import HttpResponseBadRequest, HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import CreateView, ListView

from accounts.models import FollowRelation
from mysite.settings import LOGIN_REDIRECT_URL
from tweets.models import Tweet

from .forms import SignupForm

User = get_user_model()


class SignupView(CreateView):
    form_class = SignupForm
    template_name = "accounts/signup.html"
    success_url = reverse_lazy(LOGIN_REDIRECT_URL)

    def form_valid(self, form):
        response = super().form_valid(form)
        username = form.cleaned_data["username"]
        password = form.cleaned_data["password1"]
        user = authenticate(self.request, username=username, password=password)
        login(self.request, user)
        return response


class UserProfileView(LoginRequiredMixin, ListView):
    model = Tweet
    template_name = "accounts/profile.html"
    paginate_by = 10

    def get_queryset(self):
        username = self.kwargs.get("username")
        self.user = get_object_or_404(User, username=username)
        return Tweet.objects.select_related("author").prefetch_related("likes").filter(author=self.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["target_user"] = self.user
        context["following_count"] = self.user.following.count()
        context["followed_count"] = self.user.followed.count()
        context["is_followed"] = self.user.followed.filter(following_user=self.request.user).exists()
        tweets = context["object_list"]
        for tweet in tweets:
            tweet.is_liked = self.request.user in tweet.likes.all()

        return context


class FollowView(LoginRequiredMixin, View):
    template_name = "accounts/profile.html"

    def post(self, request, username):
        following = request.user
        followed = get_object_or_404(User, username=username)

        follow_relation = FollowRelation(following_user=following, followed_user=followed)

        try:
            follow_relation.full_clean()
        except ValidationError as e:
            return HttpResponseBadRequest(e.messages)

        follow_relation.save()

        return HttpResponseRedirect(reverse("tweets:home"))


class UnFollowView(LoginRequiredMixin, View):
    template_name = "accounts/profile.html"

    def post(self, request, username):
        following = request.user
        followed = get_object_or_404(User, username=username)

        follow_relation = FollowRelation.objects.filter(following_user=following, followed_user=followed)

        if follow_relation.exists():
            follow_relation.delete()
        else:
            return HttpResponseBadRequest("存在しないフォローです")

        return HttpResponseRedirect(reverse("tweets:home"))


class FollowingListView(LoginRequiredMixin, ListView):
    model = FollowRelation
    template_name = "accounts/following_list.html"

    def get_queryset(self):
        username = self.kwargs.get("username")
        self.user = get_object_or_404(User, username=username)
        return FollowRelation.objects.select_related("followed_user").filter(following_user=self.user)


class FollowerListView(LoginRequiredMixin, ListView):
    model = FollowRelation
    template_name = "accounts/follower_list.html"

    def get_queryset(self):
        username = self.kwargs.get("username")
        self.user = get_object_or_404(User, username=username)
        return FollowRelation.objects.select_related("following_user").filter(followed_user=self.user)

templates/accounts/detail.html
{% extends "base.html" %}

{% block title %}Accounts Detail{% endblock %}

{% block content %}

<div>
    <h1>{{ profile.username }}さんのプロフィールです</h1>
    <p><a href="{% url 'tweets:create' %}">Tweetする</span></a></p>
    <a href="{% url 'accounts:logout' %}">Log out</a>
</div>

{% for tweet in tweets %}
    <div>
        <p>published: {{ tweet.published_date }}</p>
        <h4><a href="">{{ tweet.author }}</a></h4>
        <p><a href="{% url 'tweets:detail' pk=tweet.pk %}">{{ tweet.text|linebreaksbr }}</a></p>
        <hr>
    </div>
{% endfor %}

{% endblock %}

templates/accounts/follower_list.html
{% extends "base.html" %}

{% block title %}Follower{% endblock %}

{% block content %}
    <h1>フォロワー</h1>
    {% for relation in followrelation_list %}
        {{ relation.following_user }}
        <hr>
    {% endfor %}
    <div>
        <a href="{{request.META.HTTP_REFERER}}">戻る</a>
    </div>
{% endblock %}

templates/accounts/following_list.html
{% extends "base.html" %}

{% block title %}Follow{% endblock %}

{% block content %}
    <h1>フォロー</h1>
    {% for relation in followrelation_list %}
        {{ relation.followed_user }}
        <hr>
    {% endfor %}
    <div>
        <a href="{{request.META.HTTP_REFERER}}">戻る</a>
    </div>
{% endblock %}

templates/accounts/login.html
{% extends "base.html" %}

{% block title %}Log in{% endblock %}

{% block content %}
    <form method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <button type="submit">ログイン</button>
    </form>
{% endblock %}

templates/accounts/profile.html
{% extends "base.html" %}

{% block title %}Accounts Detail{% endblock %}

{% block content %}
    <div>
        <h1>{{ target_user }}さんのプロフィールです</h1>
        <p><a href="{% url 'accounts:following_list' username=target_user %}">フォロー:{{ following_count }}</a><a href="{% url 'accounts:follower_list' username=target_user %}"><span>フォロワー:{{ followed_count }}</span></a></p>
    {% if user != target_user %}
        {% if is_followed %}
            <form method="POST" action="{% url 'accounts:unfollow' username=target_user %}">
                {% csrf_token %}
                <button type="submit">フォロー解除</button>
            </form>
        {% else %}
            <form method="POST" action="{% url 'accounts:follow' username=target_user %}">
                {% csrf_token %}
                <button type="submit">フォローする</button>
            </form>
        {% endif %}
    {% endif %}
    </div>
    <div>
        <p><a href="{% url 'tweets:create' %}">Tweetする</a></p>
        <a href="{% url 'accounts:logout' %}">Log out</a>
    </div>

    {% for tweet in tweet_list %}
        {% include "tweets/show_tweet.html" %}
    {% endfor %}
    <div>
        <a href="{{request.META.HTTP_REFERER}}">戻る</a>
    </div>
{% endblock %}

templates/accounts/signup.html
{% extends "base.html" %}

{% block title %}Sign Up{% endblock %}

{% block content %}
    <form method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <button type="submit">ユーザー登録</button>
    </form>
{% endblock %}