accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.SignupView.as_view(), name="signup"),
    path("login/", auth_views.LoginView.as_view(template_name="accounts/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("<str:username>/", views.UserProfileView.as_view(), name="profile"),
    path("<str:username>/follow/", views.FollowView.as_view(), name="follow"),
    path("<str:username>/unfollow/", views.UnFollowView.as_view(), name="unfollow"),
    path("<str:username>/following_list/", views.FollowingListView.as_view(), name="following_list"),
    path("<str:username>/follower_list/", views.FollowerListView.as_view(), name="follower_list"),
]

mysite/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("tweets/", include("tweets.urls")),
    path("", include("welcome.urls")),
]

if settings.SQL_DEBUG:
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

tweets/urls.py
from django.urls import path

from . import views

app_name = "tweets"

urlpatterns = [
    path("home/", views.HomeView.as_view(), name="home"),
    path("create/", views.TweetCreateView.as_view(), name="create"),
    path("<int:pk>/", views.TweetDetailView.as_view(), name="detail"),
    path("<int:pk>/delete/", views.TweetDeleteView.as_view(), name="delete"),
    path("<int:pk>/like/", views.LikeView.as_view(), name="like"),
    path("<int:pk>/unlike/", views.UnLikeView.as_view(), name="unlike"),
]

tweets/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone


class Tweet(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="author")
    text = models.CharField(max_length=280)
    created_at = models.DateTimeField(default=timezone.now, editable=False)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, through="Like", related_name="likes")

    def __str__(self):
        return self.text


class Like(models.Model):
    liking_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="liking_user")
    liked_tweet = models.ForeignKey(Tweet, on_delete=models.CASCADE, related_name="liked_tweet")

    class Meta:
        constraints = [
            # 重複するリレーションは登録できない
            models.UniqueConstraint(
                fields=["liking_user", "liked_tweet"],
                condition=models.Q(liking_user__isnull=False, liked_tweet__isnull=False),
                name="unique_like_relation",
                violation_error_message="同じツイートを複数回いいねすることはできません",
            ),
        ]

tweets/forms.py
from django import forms

from .models import Tweet


class TweetForm(forms.ModelForm):
    text = forms.CharField(widget=forms.Textarea())

    class Meta:
        model = Tweet
        fields = ("text",)

tweets/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView, DeleteView, DetailView, ListView

from .forms import TweetForm
from .models import Like, Tweet

User = get_user_model()


class HomeView(LoginRequiredMixin, ListView):
    model = Tweet
    template_name = "tweets/home.html"
    queryset = Tweet.objects.select_related("author").prefetch_related("likes")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user

        tweets = context["object_list"]

        for tweet in tweets:
            tweet.is_liked = user in tweet.likes.all()

        return context


class TweetCreateView(LoginRequiredMixin, CreateView):
    model = Tweet
    form_class = TweetForm
    template_name = "tweets/create.html"
    success_url = reverse_lazy("tweets:home")

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class TweetDetailView(LoginRequiredMixin, DetailView):
    model = Tweet
    queryset = Tweet.objects.select_related("author")
    template_name = "tweets/detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user

        tweet = context["object"]
        tweet.is_liked = Like.objects.filter(liking_user=user, liked_tweet=tweet).exists()

        return context


class TweetDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Tweet
    queryset = Tweet.objects.select_related("author")
    template_name = "tweets/delete.html"
    success_url = reverse_lazy("tweets:home")

    def get(self, request, *args, **kwargs):
        # test_funcの方が先に呼ばれるので、getメソッド内でself.objectにアクセス可能
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)

    def test_func(self):
        self.object = self.get_object()
        return self.object.author == self.request.user


class LikeView(LoginRequiredMixin, View):
    def post(self, request, pk, *args, **kwargs):
        liked_tweet = get_object_or_404(Tweet, pk=pk)
        like_relation = Like.objects.filter(liking_user=request.user, liked_tweet=liked_tweet)

        if not like_relation.exists():
            Like.objects.create(liking_user=request.user, liked_tweet=liked_tweet)

        likes_count = liked_tweet.likes.count()

        return JsonResponse({"likes_count": likes_count})


class UnLikeView(LoginRequiredMixin, View):
    def post(self, request, pk, *args, **kwargs):
        liked_tweet = get_object_or_404(Tweet, pk=pk)

        if (like_relation := Like.objects.filter(liking_user=request.user, liked_tweet=liked_tweet)).exists():
            like_relation.delete()

        likes_count = liked_tweet.likes.count()

        return JsonResponse({"likes_count": likes_count})

templates/tweets/create.html
{% extends "base.html" %}

{% block title %}Create{% endblock %}

{% block content %}
    <div>
        <h1>新しいTweetを作成</h1>
    </div>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Tweet!</button>
    </form>
{% endblock %}

templates/tweets/delete.html
{% extends "base.html" %}

{% block title %}Are you Sure?{% endblock %}

{% block content %}
    <div>
        <h1>消すの？</h1>
    </div>
    <div>
        <p>本文: {{ object }}</p>
    </div>
    <form method="POST" class="post-form">{% csrf_token %}
        <button type="submit" class="save btn btn-default">消す!</button>
    </form>
{% endblock %}

templates/tweets/detail.html
{% extends "base.html" %}


{% block content %}
    <div>
        <p><a href="{% url 'tweets:create' %}">Tweetする</span></a></p>
        <p><a href="{% url 'accounts:logout' %}">Log out</a></p>
    </div>
        {% include "tweets/show_tweet.html" %}
    <div>
        <a href="{{request.META.HTTP_REFERER}}">戻る</a>
    </div>
{% endblock %}

templates/tweets/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
    <div>
        <h1>ようこそ{{ user.username }}さん、Homeです</h1>
        <p><a href="{% url 'tweets:create' %}">Tweetする</span></a></p>
        <p><a href="{% url 'accounts:logout' %}">Log out</a></p>
    </div>

    {% for tweet in tweet_list %}
        {% include "tweets/show_tweet.html" %}
    {% endfor %}
{% endblock %}

templates/tweets/show_tweet.html
<div>
    <hr>
    <div>
        <a href="{% url 'accounts:profile' username=tweet.author%}">{{ tweet.author }}</a>
        {{ tweet.created_at }}
        {% if tweet.author == user %}
            <a href="{% url 'tweets:delete' pk=tweet.pk %}">
                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" id="icon" x="0px" y="0px" viewBox="0 0 1000 1000" style="enable-background:new 0 0 1000 1000;" width="18" xml:space="preserve"> <path d="M840,180c0-22.1-17.9-40-40-40H620v-40c0-22.1-17.9-40-40-40H420c-22.1,0-40,17.9-40,40v40H200c-22.1,0-40,17.9-40,40v100 h41.1l40.1,660h517.6l40.1-660H840V180z M420,97h160v43H420V97z M200,178h600v64H200V178z M721.2,900H278.8l-37.6-620h517.5 L721.2,900z M520,820h-40V380h40V820z M359.1,820l-18.3-440h40l18.3,440H359.1z M640.9,820h-40l18.3-440h40L640.9,820z"/>
                    <path xmlns="http://www.w3.org/2000/svg" d="M840,180c0-22.1-17.9-40-40-40H620v-40c0-22.1-17.9-40-40-40H420c-22.1,0-40,17.9-40,40v40H200c-22.1,0-40,17.9-40,40v100 h41.1l40.1,660h517.6l40.1-660H840V180z M420,97h160v43H420V97z M200,178h600v64H200V178z M721.2,900H278.8l-37.6-620h517.5 L721.2,900z M520,820h-40V380h40V820z M359.1,820l-18.3-440h40l18.3,440H359.1z M640.9,820h-40l18.3-440h40L640.9,820z"/>
                </svg>
            </a>
        {% endif %}
    </div>
    <p>
        <a href="{% url 'tweets:detail' pk=tweet.pk%}">{{ tweet.text|linebreaksbr }}</a>
    </p>
    <div>
        <button type="submit" class="like-button"  data-tweet-pk="{{ tweet.pk }}" data-is-liked="{{ tweet.is_liked | yesno:'true, false' }}">
            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="18" height="18" viewBox="0 0 36 36" aria-hidden="true" role="img" class="iconify iconify--twemoji" preserveAspectRatio="xMidYMid meet">
                <path fill="{{ tweet.is_liked | yesno:'#BE1931, #FFFFFF' }}" d="M2.067 11.319C2.067 2.521 14.251-.74 18 9.445C21.749-.741 33.933 2.52 33.933 11.319C33.933 20.879 18 33 18 33S2.067 20.879 2.067 11.319z"/>
            </svg>
            <div class="likes-count">
                {{ tweet.likes.count }}
            </div>
        </button>
    </div>
</div>