mysite/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("tweets/", include("tweets.urls")),
    path("", include("welcome.urls")),
]

if settings.SQL_DEBUG:
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

tweets/urls.py
from django.urls import path

from . import views

app_name = "tweets"

urlpatterns = [
    path("home/", views.HomeView.as_view(), name="home"),
    path("create/", views.TweetCreateView.as_view(), name="create"),
    path("<int:pk>/", views.TweetDetailView.as_view(), name="detail"),
    path("<int:pk>/delete/", views.TweetDeleteView.as_view(), name="delete"),
    path("<int:pk>/like/", views.LikeView.as_view(), name="like"),
    path("<int:pk>/unlike/", views.UnLikeView.as_view(), name="unlike"),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <title>{% block title %}Twitter Clone{% endblock %}</title>
</head>

<body>
    <!-- header  -->
    <header class="mb-3">
        <h1><a href="{% url 'tweets:home' %}">Twitter Clone</a></h1>
    </header>
    <!-- /header  -->

    <!-- main  -->
    <main>
        {% block content %}
        {% endblock %}
    </main>
    <!-- /main  -->
    <script src="{% static 'js/toggle_like.js' %}"></script>
</body>

</html>